
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A38C7D5E5BAF630F5B34115B18D084A4'
    
_lr_action_items = {'NUMBER':([0,1,2,4,5,8,9,10,11,12,13,14,],[1,-6,-3,-5,1,-4,-8,1,-10,-7,-9,-11,]),'SYMBOL':([0,1,2,4,5,8,9,10,11,12,13,14,],[2,-6,-3,-5,2,-4,-8,2,-10,-7,-9,-11,]),'STRING':([0,1,2,4,5,8,9,10,11,12,13,14,],[4,-6,-3,-5,4,-4,-8,4,-10,-7,-9,-11,]),'RPAREN':([1,2,4,5,8,9,10,11,12,13,14,],[-6,-3,-5,11,-4,-8,14,-10,-7,-9,-11,]),'LPAREN':([0,1,2,4,5,8,9,10,11,12,13,14,],[5,-6,-3,-5,5,-4,-8,5,-10,-7,-9,-11,]),'$end':([1,2,3,4,6,7,8,11,14,],[-6,-3,-1,-5,-2,0,-4,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'list':([0,5,10,],[6,12,12,]),'toplevel':([0,],[7,]),'atom':([0,5,10,],[3,9,13,]),'exprs':([5,],[10,]),'symbol':([0,5,10,],[8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toplevel","S'",1,None,None,None),
  ('toplevel -> atom','toplevel',1,'p_toplevel','parser.py',7),
  ('toplevel -> list','toplevel',1,'p_toplevel','parser.py',8),
  ('symbol -> SYMBOL','symbol',1,'p_symbol','parser.py',13),
  ('atom -> symbol','atom',1,'p_atom','parser.py',18),
  ('atom -> STRING','atom',1,'p_atom','parser.py',19),
  ('atom -> NUMBER','atom',1,'p_atom','parser.py',20),
  ('atom -> list','atom',1,'p_atom','parser.py',21),
  ('exprs -> atom','exprs',1,'p_exprs_1','parser.py',26),
  ('exprs -> exprs atom','exprs',2,'p_exprs_2','parser.py',33),
  ('list -> LPAREN RPAREN','list',2,'p_list_0','parser.py',40),
  ('list -> LPAREN exprs RPAREN','list',3,'p_list_1','parser.py',45),
]
