
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '13E3E4ED154F7B9EE3C3305241F97E63'
    
_lr_action_items = {'NUMBER':([0,2,3,4,5,8,10,11,12,13,14,15,],[4,-6,-7,-8,4,-5,-12,-9,-10,4,-13,-11,]),'RPAREN':([2,3,4,5,8,10,11,12,13,14,15,],[-6,-7,-8,10,-5,-12,-9,-10,14,-13,-11,]),'LPAREN':([0,2,3,4,5,8,10,11,12,13,14,15,],[5,-6,-7,-8,5,-5,-12,-9,-10,5,-13,-11,]),'SYMBOL':([0,2,3,4,5,8,10,11,12,13,14,15,],[8,-6,-7,-8,8,-5,-12,-9,-10,8,-13,-11,]),'$end':([0,1,2,3,4,6,7,8,9,10,14,],[-4,-3,-6,-7,-8,0,-1,-5,-2,-12,-13,]),'STRING':([0,2,3,4,5,8,10,11,12,13,14,15,],[3,-6,-7,-8,3,-5,-12,-9,-10,3,-13,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'list':([0,5,13,],[1,11,11,]),'symbol':([0,5,13,],[2,2,2,]),'toplevel':([0,],[6,]),'atom':([0,5,13,],[7,12,15,]),'empty':([0,],[9,]),'exprs':([5,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toplevel","S'",1,None,None,None),
  ('toplevel -> atom','toplevel',1,'p_toplevel','parser.py',7),
  ('toplevel -> empty','toplevel',1,'p_toplevel','parser.py',8),
  ('toplevel -> list','toplevel',1,'p_toplevel','parser.py',9),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',14),
  ('symbol -> SYMBOL','symbol',1,'p_symbol','parser.py',19),
  ('atom -> symbol','atom',1,'p_atom','parser.py',29),
  ('atom -> STRING','atom',1,'p_atom','parser.py',30),
  ('atom -> NUMBER','atom',1,'p_atom','parser.py',31),
  ('atom -> list','atom',1,'p_atom','parser.py',32),
  ('exprs -> atom','exprs',1,'p_exprs_1','parser.py',37),
  ('exprs -> exprs atom','exprs',2,'p_exprs_2','parser.py',44),
  ('list -> LPAREN RPAREN','list',2,'p_list_0','parser.py',51),
  ('list -> LPAREN exprs RPAREN','list',3,'p_list_1','parser.py',56),
]
